"""Golden tests for the deterministic QC layer.

These probes produce the numbers that block a release, so they are tested
against real audio with known ground truth -- not mocked. The fixtures are
generated by scripts/make_fixtures.sh with exact utterance boundaries, which
is what makes assertion to the millisecond legitimate.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from media.qc import (
    Interval,
    measure_dub,
    measure_loudness,
    measure_subtitles,
    voiced_intervals,
)
from media.qc.profiles import UnknownMeasurement, check, check_all, profile
from media.qc.sync import sync_offset
from media.qc.types import Measurement

FIXTURES = Path(__file__).resolve().parents[1] / "media" / "fixtures"

# Ground truth baked into the fixture generator.
REFERENCE = [Interval(500, 2000), Interval(3000, 5000), Interval(6500, 9000)]
TOLERANCE_MS = 25.0  # silencedetect resolution at a 150 ms minimum gap


# --------------------------------------------------------------------------
# boundary detection
# --------------------------------------------------------------------------

def test_reference_boundaries_recovered_exactly():
    found = voiced_intervals(FIXTURES / "ref_scene14.wav")
    assert len(found) == len(REFERENCE)
    for got, want in zip(found, REFERENCE):
        assert abs(got.start_ms - want.start_ms) < TOLERANCE_MS
        assert abs(got.end_ms - want.end_ms) < TOLERANCE_MS


def test_probe_is_deterministic():
    """Same bytes in, same number out -- the property that lets this carry an SLO."""
    a = voiced_intervals(FIXTURES / "dub_de_bad.wav")
    b = voiced_intervals(FIXTURES / "dub_de_bad.wav")
    assert [(i.start_ms, i.end_ms) for i in a] == [(i.start_ms, i.end_ms) for i in b]


# --------------------------------------------------------------------------
# the discriminator the repair loop branches on
# --------------------------------------------------------------------------

def test_good_dub_is_within_tolerance_and_reads_as_systematic_drift():
    """A uniformly late stem is a muxing/padding fault: shifting the track fixes it."""
    measured = voiced_intervals(FIXTURES / "dub_fr_ok.wav")
    m = sync_offset(REFERENCE, measured)

    assert m.value == pytest.approx(40.0, abs=TOLERANCE_MS)
    assert m.detail["drift_is_systematic"] is True
    assert check(m, "fr-FR").passed


def test_bad_dub_fails_and_reads_as_scattered_drift():
    """Scattered drift means lines do not fit their slots. Retiming cannot fix
    this, and the agent must replan to a rewrite. This assertion is the demo."""
    measured = voiced_intervals(FIXTURES / "dub_de_bad.wav")
    m = sync_offset(REFERENCE, measured)

    assert m.value > 400.0
    assert m.detail["drift_is_systematic"] is False
    assert m.detail["worst_utterance_index"] == 2

    result = check(m, "de-DE")
    assert not result.passed
    assert result.margin < 0  # failing, and by how much


def test_utterance_count_mismatch_is_reported_not_swallowed():
    m = sync_offset(REFERENCE, [Interval(500, 2000), Interval(3000, 5000)])
    assert m.detail["anomaly"] is not None
    assert "utterance_count_mismatch" in m.detail["anomaly"]


def test_speech_rate_excludes_silence():
    ms = measure_dub(FIXTURES / "dub_fr_ok.wav", REFERENCE, word_count=14)
    rate = next(m for m in ms if m.key == "quality.speech_rate_wpm")
    # 14 words over ~6.0 s of voiced audio, not over the 10 s file duration.
    assert rate.value == pytest.approx(140.0, abs=8.0)
    assert rate.detail["voiced_ms"] < 7000


# --------------------------------------------------------------------------
# loudness
# --------------------------------------------------------------------------

def test_loudness_returns_integrated_and_true_peak():
    ms = measure_loudness(FIXTURES / "dub_fr_ok.wav")
    keys = {m.key for m in ms}
    assert keys == {
        "delivery.audio_loudness_lufs",
        "delivery.audio_true_peak_dbtp",
    }
    assert all(m.value < 0 for m in ms)


def test_loudness_is_judged_as_a_two_sided_band():
    ms = measure_loudness(FIXTURES / "dub_fr_ok.wav")
    checks = {c.measurement.key: c for c in check_all(ms, "de-DE")}
    band = checks["delivery.audio_loudness_deviation_lu"]

    assert band.threshold == 1.0
    assert band.measurement.detail["target_lufs"] == -23.0
    # fixture sits near -12.6 LUFS, far above target: must fail
    assert not band.passed


# --------------------------------------------------------------------------
# subtitles
# --------------------------------------------------------------------------

SRT_OK = """1
00:00:00,500 --> 00:00:02,000
The signal came from the ridge.

2
00:00:03,000 --> 00:00:05,000
Then we move before first light.
"""

SRT_TOO_FAST = """1
00:00:00,500 --> 00:00:01,000
An extremely long line of dialogue crammed into half a second.
"""


def test_subtitle_reading_rate(tmp_path):
    p = tmp_path / "ok.srt"
    p.write_text(SRT_OK, encoding="utf-8")
    ms = {m.key: m for m in measure_subtitles(p)}

    assert ms["delivery.subtitle_reading_rate_cps"].value < 20
    assert ms["delivery.subtitle_max_lines"].value == 1
    assert check(ms["delivery.subtitle_reading_rate_cps"], "fr-FR").passed


def test_subtitle_too_fast_fails_and_names_the_cue(tmp_path):
    p = tmp_path / "fast.srt"
    p.write_text(SRT_TOO_FAST, encoding="utf-8")
    m = next(
        m for m in measure_subtitles(p)
        if m.key == "delivery.subtitle_reading_rate_cps"
    )
    assert not check(m, "fr-FR").passed
    assert m.detail["worst_cue_index"] == 1
    assert "extremely long line" in m.detail["worst_cue_text"]


def test_japanese_has_a_stricter_reading_rate_than_french(tmp_path):
    """Market rules genuinely differ; the same file can pass one and fail another."""
    p = tmp_path / "ok.srt"
    p.write_text(SRT_OK, encoding="utf-8")
    m = next(
        m for m in measure_subtitles(p)
        if m.key == "delivery.subtitle_reading_rate_cps"
    )
    assert profile("ja-JP")["delivery"]["subtitle_max_cps"] < \
        profile("fr-FR")["delivery"]["subtitle_max_cps"]
    assert check(m, "fr-FR").passed
    assert not check(m, "ja-JP").passed


# --------------------------------------------------------------------------
# the safety property
# --------------------------------------------------------------------------

def test_unjudged_measurement_raises_rather_than_passing():
    """A probe whose output has no threshold rule must never look like a pass."""
    rogue = Measurement(key="quality.vibes", value=1.0, unit="ratio", method="x")
    with pytest.raises(UnknownMeasurement):
        check(rogue, "de-DE")
