"""Render the wake receiver's own log as a frame of the film.

    python scripts/wakelog.py

The one moment the film asserts and does not show: Grafana deciding a market
cannot ship, and calling the agents about it. The alert rule page proves the
rule exists and is firing. It does not prove anything answered.

This reads the deployed receiver's log out of Cloud Logging and writes
`ui/wakelog.html` with the lines it found -- the real timestamps, the real
fingerprints, the real markets. Generated rather than typed, so the frame
cannot drift from what the service actually did. If nothing has fired in the
window, it fails instead of writing a page: an empty log is the truthful
answer, and a demo that invents one is exactly the thing this project is an
argument against.
"""

from __future__ import annotations

import html
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "ui" / "wakelog.html"
PROJECT = "grafana-508011"
SERVICE = "continuity-wake"

# Only lines the receiver itself wrote about an alert. Cloud Run's own
# lifecycle chatter -- probes, instance starts, the MCP server's warning about
# loopback auth -- is true and has nothing to do with the claim being made.
KEEP = re.compile(r"\b(accepted|refused|rejected)\b")

TEMPLATE = """<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<title>continuity-wake</title>
<!-- Generated by scripts/wakelog.py from Cloud Logging. Do not edit. -->
<style>
  :root {{
    color-scheme: dark;
    --bg: #0b0b0a; --ink: #f6f5f1; --ink-2: #a8a69c; --ink-3: #6b6960;
    --ink-4: #4a4842; --line: #262623; --good-ink: #67d167;
    --warn: #e0b558; --blue: #8ab8f2;
    --mono: ui-monospace, "JetBrains Mono", "SF Mono", Consolas, monospace;
    --sans: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
  }}
  * {{ box-sizing: border-box; }}
  html, body {{ height: 100%; }}
  body {{
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.6 var(--sans); display: flex; align-items: center;
    justify-content: center; -webkit-font-smoothing: antialiased;
  }}
  .wrap {{ width: min(1560px, 90vw); padding-bottom: 6vh; }}
  h1 {{ margin: 0 0 4px; font: 600 13px/1 var(--sans); letter-spacing: .2em;
       text-transform: uppercase; color: var(--ink-3); }}
  h1 span {{ color: var(--ink); }}
  p.where {{ margin: 0 0 22px; font: 13px/1.6 var(--mono);
             color: var(--ink-4); }}
  pre {{ margin: 0; padding: 26px 28px; background: #080807;
        border: 1px solid var(--line); border-radius: 8px;
        font: 20px/2.05 var(--mono); overflow: hidden; }}
  .t {{ color: var(--ink-4); }}
  .lv {{ color: var(--blue); }}
  .ok {{ color: var(--good-ink); }}
  .rule {{ color: var(--ink); }}
  .arrow {{ color: var(--warn); }}
</style>
</head>
<body>
  <div class="wrap">
    <h1>Cloud Run · <span>continuity-wake</span></h1>
    <p class="where">gcloud logging read
      resource.labels.service_name="continuity-wake"</p>
    <pre>{body}</pre>
  </div>
</body>
</html>
"""


def read() -> list[str]:
    gcloud = shutil.which("gcloud") or "gcloud"
    result = subprocess.run(
        [gcloud, "logging", "read",
         'resource.type="cloud_run_revision" AND '
         f'resource.labels.service_name="{SERVICE}"',
         "--project", PROJECT, "--limit", "80", "--freshness", "12h",
         "--format", "value(textPayload)"],
        capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("gcloud logging read failed:\n" + result.stderr[-600:])
    lines = [line.strip() for line in result.stdout.splitlines()
             if KEEP.search(line)]
    # Newest first out of the API; a log reads downwards.
    return list(reversed(lines))


def markup(line: str) -> str:
    """Colour the parts that carry the claim, and nothing else."""
    match = re.match(
        r"^(?P<t>\S+ \S+)\s+(?P<lv>\w+)\s+(?P<verb>accepted|refused|rejected)"
        r"\s+(?P<rule>\S+)\s+(?P<arrow>->)\s+(?P<act>\S+)\s*$", line)
    if not match:
        return html.escape(line)
    g = {k: html.escape(v) for k, v in match.groupdict().items()}
    return (f'<span class="t">{g["t"]}</span>  '
            f'<span class="lv">{g["lv"]}</span>   '
            f'<span class="ok">{g["verb"]}</span>  '
            f'<span class="rule">{g["rule"]}</span> '
            f'<span class="arrow">{g["arrow"]} {g["act"]}</span>')


def main() -> int:
    lines = read()
    if not lines:
        print("no alert lines in the last 12 hours -- nothing to show, and "
              "inventing one is not an option", file=sys.stderr)
        return 1
    # The tail, because the newest firings are the ones a viewer can check
    # against the board they were just looking at.
    body = "\n".join(markup(line) for line in lines[-9:])
    PAGE.write_text(TEMPLATE.format(body=body), encoding="utf-8")
    print(f"  {PAGE}   {len(lines)} alert line(s), showing the last "
          f"{min(9, len(lines))}")
    for line in lines[-9:]:
        print("   ", line[:110])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
